version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    mem_limit: 1g
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=senha
      - POSTGRES_USER=usuario
      - POSTGRES_DB=vagaToo